<?php

namespace App\Form;

use App\Entity\ActivitySearch;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ActivitySearchFormType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('category', ChoiceType::class, [
                'choices'=>[
                    'Artisanat'=>'Artisanat',
                    'Blanchisseur'=>'Blanchisseur',
                    'Boulangerie'=>'Boulangerie',
                    'Boutiquier'=>'Boutiquier',
                    'Clinique'=>'Clinique',
                    'Commerçant'=>'Commerçant',
                    'Cordonniers'=>'Cordonniers',
                    'Cosmetique'=>'Cosmetique',
                    'Déménagement'=>'Déménagement',
                    'Electricien'=>'Electricien',
                    'Garage Auto'=>'Garage Auto',
                    'Garage Moto'=>'Garage Moto',
                    'Garage vélo'=>'Garage vélo',
                    'Menuisier'=>'Menuisier',
                    'Menuisier-metal'=>'Métallurgie',
                    'Plomberie'=>'Plomberie',
                    'Salon de coiffure H/F'=>'Salon de Coiffure',
                    'Salon de coiffure F'=>'Salon de Coiffure Femme',
                    'Salon de Coiffure H'=>'Salon de Coiffure H',
                    'Restauration'=>'Restauration',
                    'Couture'=>'Couture',
                    'Reparateur'=>'Reparateur',
                ]
            ])
            ->add('address',null, [
                'attr'=>['placeholder'=>"Ville, Commune, Quartier"],
                'required'=>true
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => ActivitySearch::class,
            'csrf_protection'=>false,
            'method'=>'get'
        ]);
    }

    public function getBlockPrefix(): string
    {
        return ""; // TODO: Change the autogenerated stub
    }
}
