<?php

namespace App\Form;

use App\Entity\ApartFilter;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ApartFilterFormType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('location', null, [
                'attr'=>['placeholder'=>'Ville, commune, quartier'],
                'required'=>true
            ])
            ->add('price', NumberType::class, [
                'attr'=>['placeholder'=>'500000'],
                'required'=>true
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => ApartFilter::class,
            'method'=>'GET',
            'csrf_protection'=>false
        ]);
    }

    public function getBlockPrefix(): string
    {
        return ""; // TODO: Change the autogenerated stub
    }
}
